baseURL = 'https://thebytenewspaper.github.io/'
languageCode = 'en-us'
title = 'The Byte'

[params]
defaultImage = "/images/default.jpg"
homepageHeadline = "Creative stories and articles showcasing our writers' creative expression"
homepageSubheadline = "We are a close-knit community of creative writers that come together fortnightly to write creative stories and articles that we then publish on this lovely blog for you to enjoy and admire. We thank you for your support and appreciation, please leave a like on our articles and share them for others to admire too!"

instagramUrl = ""
email = ""

